name: "CI"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  dev:
    name: Dev
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Dependencies
        run: npm ci

      - name: Lint
        run: npx eslint meshcore-bot.js

  prod:
    name: Prod
    runs-on: ubuntu-latest
    needs:
      - dev
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Dependencies
        run: npm ci --production

      - name: Help
        run: node meshcore-bot.js --help

      - name: Smoke Test
        run: node meshcore-bot.js --port "gibtesnicht" | grep "cannot open gibtesnicht"
